{{- if .Values.mongodb.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "net4255.fullname" . }}-mongodb-init
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-wait": "false"
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mongo-init
          image: {{ .Values.mongodb.image }}
          command:
            - /bin/bash
            - -c
            - |
              echo "Waiting for MongoDB pods to be ready..."
              until mongosh --host {{ include "net4255.fullname" . }}-mongodb-0.{{ include "net4255.fullname" . }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local --quiet --eval "db.adminCommand({ping: 1})"; do
                echo "Waiting for mongodb-0..."
                sleep 5
              done
              
              echo "Checking if replica set is already initialized..."
              RS_STATUS=$(mongosh --host {{ include "net4255.fullname" . }}-mongodb-0.{{ include "net4255.fullname" . }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local --quiet --eval "try { rs.status().ok } catch(e) { 0 }" || echo "0")
              
              if [ "$RS_STATUS" != "1" ]; then
                echo "Initializing replica set..."
                mongosh --host {{ include "net4255.fullname" . }}-mongodb-0.{{ include "net4255.fullname" . }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local --quiet --eval '
                  rs.initiate({
                    _id: "{{ .Values.mongodb.replicaSet.name }}",
                    members: [
                      { _id: 0, host: "{{ include "net4255.fullname" . }}-mongodb-0.{{ include "net4255.fullname" . }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.mongodb.port }}" },
                      { _id: 1, host: "{{ include "net4255.fullname" . }}-mongodb-1.{{ include "net4255.fullname" . }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.mongodb.port }}" },
                      { _id: 2, host: "{{ include "net4255.fullname" . }}-mongodb-2.{{ include "net4255.fullname" . }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.mongodb.port }}" }
                    ]
                  })
                '
                echo "Replica set initialized"
              else
                echo "Replica set already initialized"
              fi
              
              echo "Waiting for replica set election..."
              sleep 10
              mongosh --host {{ include "net4255.fullname" . }}-mongodb-0.{{ include "net4255.fullname" . }}-mongodb-headless.{{ .Release.Namespace }}.svc.cluster.local --quiet --eval 'rs.status().members.forEach(m => print(m.name + " - " + m.stateStr))'
{{- end }}
