{{- if .Values.mongodb.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "net4255.fullname" . }}-mongodb
spec:
  serviceName: {{ include "net4255.fullname" . }}-mongodb-headless
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ include "net4255.fullname" . }}-mongodb
  template:
    metadata:
      labels:
        app: {{ include "net4255.fullname" . }}-mongodb
    spec:
      volumes:
      - name: mongo-db
        emptyDir: {}
      containers:
        - name: mongodb
          image: {{ .Values.mongodb.image }}
          args: 
            - "--bind_ip_all"
            - "--replSet"
            - {{ .Values.mongodb.replicaSet.name | quote }}
            - "--wiredTigerCacheSizeGB"
            - "0.25"
          ports:
            - containerPort: {{ .Values.mongodb.port }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.mongodb.port }}
            initialDelaySeconds: 45
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 6
          resources:
            requests:
              cpu: {{ .Values.mongodb.resources.requests.cpu }}
              memory: {{ .Values.mongodb.resources.requests.memory }}
            limits:
              cpu: {{ .Values.mongodb.resources.limits.cpu }}
              memory: {{ .Values.mongodb.resources.limits.memory }}
          volumeMounts:
            - name: mongo-db
              mountPath: /data/db
            - name: mongo-data
              mountPath: /data/pvc
  volumeClaimTemplates:
    - metadata:
        name: mongo-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: {{ .Values.mongodb.storage.storageClassName }}
        resources:
          requests:
            storage: {{ .Values.mongodb.storage.size }}
{{- end }}
