{{- if .Values.mongodb.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mongodb-network-policy
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
    app: {{ include "net4255.fullname" . }}-mongodb
spec:
  podSelector:
    matchLabels:
      app: {{ include "net4255.fullname" . }}-mongodb
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: webdb
        - podSelector:
            matchLabels:
              app: {{ include "net4255.fullname" . }}-mongodb
      ports:
        - protocol: TCP
          port: {{ .Values.mongodb.port }}
{{- end }}
