apiVersion: v1
kind: Service
metadata:
  name: {{ include "net4255.fullname" . }}-redis
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
    protocol: TCP
  selector:
    app: {{ include "net4255.fullname" . }}-redis
