apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
    app: webdb
spec:
  {{- if not .Values.webdb.autoscaling.enabled }}
  replicas: {{ .Values.webdb.replicas }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
        {{- include "net4255.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: webdb
          image: {{ printf "%s:%s" .Values.image.repository .Values.webdb.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_MODULE
              value: "app"
            - name: MONGO_HOST
              valueFrom:
                configMapKeyRef:
                  name: {{ include "net4255.fullname" . }}-mongo
                  key: MONGO_HOST
            - name: MONGO_PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "net4255.fullname" . }}-mongo
                  key: MONGO_PORT
            - name: MONGO_DB
              value: {{ .Values.webdb.mongo.db | quote }}
            - name: MONGO_COLLECTION
              value: {{ .Values.webdb.mongo.collection | quote }}
            - name: REDIS_HOST
              value: "net4255-redis"
            - name: REDIS_PORT
              value: "6379"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webdb
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
    app: webdb
spec:
  type: ClusterIP
  selector:
    app: webdb
  ports:
    - port: 5000
      targetPort: 5000
