apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
    app: webnodb
spec:
  {{- if not .Values.webnodb.autoscaling.enabled }}
  replicas: {{ .Values.webnodb.replicas }}
  {{- end }}
  selector:
    matchLabels:
      app: webnodb
  template:
    metadata:
      labels:
        app: webnodb
        {{- include "net4255.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: webnodb
          image: {{ printf "%s:%s" .Values.image.repository .Values.webnodb.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: APP_MODULE
              value: "app_nodb"
          ports:
            - containerPort: 5000
          resources:
            requests:
              cpu: {{ .Values.resources.requests.cpu | quote }}
              memory: {{ .Values.resources.requests.memory | quote }}
            limits:
              cpu: {{ .Values.resources.limits.cpu | quote }}
              memory: {{ .Values.resources.limits.memory | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webnodb
  labels:
    {{- include "net4255.labels" . | nindent 4 }}
    app: webnodb
spec:
  type: ClusterIP
  selector:
    app: webnodb
  ports:
    - port: 5000
      targetPort: 5000
