# AWS EKS overrides for net4255-chart

image:
  repository: "<AWS_ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/net4255"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: net4255-app
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::<AWS_ACCOUNT_ID>:role/net4255-app-irsa-role

webdb:
  tag: webdb-v7

webnodb:
  tag: webnodb-v2

mongodb:
  enabled: true
  replicas: 3
  storage:
    size: 5Gi
    storageClassName: gp3-net4255
    createStorageClass: true
    ebs:
      type: gp3
      fsType: ext4
      iops: "3000"
      throughput: "125"

ingress:
  enabled: true
  className: alb
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/success-codes: 200-399
  hosts:
    webdb: webdb.net4255.example.com
    webnodb: webnodb.net4255.example.com

prometheus:
  enabled: true
  serviceMonitor:
    enabled: true
  alertRules:
    enabled: true
